module PaysonAPI
  module Errors
    class RemoteError < PaysonAPIError
      ERROR_CODES = {
        '500000' => "System error.",
        '520002' => "Internal error.",
        '520003' => "Authentication failed; Credentials were not valid.",
        '520004' => "The merchant account is restricted.",
        '520005' => "The merchant account is locked.",
        '520006' => "The requested API endpoint is unknown.",
        '529038' => "Error while executing payment.",
        '539041' => "An email account is not receive enabled.",
        '539043' => "An email account is not send enabled.",
        '559044' => "A receiver's preferences denied the payment.",
        '560027' => "Unrecognized fees payer type.",
        '579007' => "Payment request number of receivers exceeds the maximum.",
        '579008' => "Number of primary receivers exceeds 1.",
        '579017' => "Primary receiver amount for chained payment must not be less than sum of other receiver amounts.",
        '579033' => "Sender and each receiver must all have different accounts.",
        '579040' => "Two receivers belong to the same Payson user account.",
        '579042' => "The tracking ID already exists and cannot be duplicated.",
        '579045' => "This request would exceed the receiving limit for an account.",
        '579047' => "This request would exceed the purse limit for an account.",
        '579048' => "This request would exceed the sending limit for an account.",
        '579049' => "The payment request you are looking for was not found in our system.",
        '580001' => "Invalid request - the request did not pass our basic validation.",
        '580021' => "Invalid parameter - too long.",
        '580022' => "Your request was invalid. Check the parameter of the error to see which is invalid.",
        '580023' => "A receiver was given more than once in the request.",
        '580027' => "Unsupported currency code.",
        '580028' => "A URL supplied with the request is malformed.",
        '580029' => "A required parameter was not provided. Check the error parameter list.",
        '589018' => "Invalid pay key.",
        '589052' => "The transaction ID was not found in our system.",
        '589053' => "All payment methods have been disabled for this combination of funding constraint, merchant and receiver.",
        '590001' => "The total amount specified for receivers does not match the total amount specified by the order items.",
        '590005' => "Not all related order item parameters where specified. All or none of unitPrice, quantity, taxPercentage and sku must be set.",
        '590006' => "Invoice requires one reciever.",
        '590007' => "Invoice requires fee on reciever.",
        '590008' => "Invoice requires that order items are specified.",
        '590009' => "Invoice payments are not available to this merchant.",
        '590010' => "The requested action is not possible in the current state of the payment.",
        '590011' => "The amount on the invoice is below the minimum limit.",
        '590012' => "Invoice does not support the selected currency.",
        '590013' => "The invoice fee out of the valid range (0-30 SEK).",
        '590014' => "The invoice fee can only be specified for invoices.",
        '590015' => "The receiver is not allowed to receive invoices.",
        '590016' => "The sender and reciever is the same user.",
        '590017' => "Invoice is frozen and cannot be updated.",
        '590018' => "The requested action is not possible for the current type of payment.",
        '590021' => "The funding constraint INVOICE cannot be combined with other funding constraints."
      }
    end
  end
end
